{"uuid": "58a90fa1-a848-4102-9ecc-62846f41c76d", "befores": [{"name": "login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: session timed out or not found\n\n", "trace": "  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 17, in login_page\n    return LoginPage(driver=driver)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\pages\\base_page.py\", line 20, in __init__\n    self.driver.implicitly_wait(10)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1148, in implicitly_wait\n    self.execute(Command.SET_TIMEOUTS, {\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1640018173253, "stop": 1640018195643}], "start": 1640018173253, "stop": 1640018197197}