{"uuid": "2638126e-24ea-4274-b53e-649729b31c26", "children": ["54697ac4-87d2-441c-8613-fd40a98ed5b7"], "befores": [{"name": "driver", "status": "passed", "steps": [{"name": "Init browser", "status": "passed", "start": 1640018013321, "stop": 1640018172100}], "start": 1640018013320, "stop": 1640018172136}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: session timed out or not found\n\n", "trace": "  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 76, in driver\n    browser.quit()\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 949, in quit\n    self.execute(Command.QUIT)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1640018197296, "stop": 1640018198081}], "start": 1640018013320, "stop": 1640018198082}