{"name": "test_accept_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'access'", "trace": "self = <test_db.TestMysql object at 0x000001BAFB2F8DC0>\n\n    @allure.epic('Awesome test application')\n    @allure.feature('DB tests')\n    @allure.story('Accept user')\n    def test_accept_user(self):\n        accept_user = TestUser(\n            username=\"acceptuser\",\n            password=\"1234\",\n            email=\"acceptusere@test.ru\"\n        )\n        self.api_client.create_user(accept_user.username, accept_user.password, accept_user.email)\n        self.api_client.block_user(accept_user.username)\n        self.api_client.accept_user(accept_user.username)\n        found_user = self.mysql.session.query(TestUser) \\\n            .filter(TestUser.username == accept_user.username) \\\n            .filter(TestUser.password == accept_user.password) \\\n            .filter(TestUser.email == accept_user.email).first()\n>       assert found_user.access == 1\nE       AttributeError: 'NoneType' object has no attribute 'access'\n\ntests\\db_test\\test_db.py:79: AttributeError"}, "start": 1640010801915, "stop": 1640010802054, "uuid": "ef7e3b18-0ae4-4b50-af32-6943e4bb0caa", "historyId": "11273d533fc76839336a35fa0fc173a3", "testCaseId": "e340fb0e57b7bc8c4acadf3f570a45ce", "fullName": "tests.db_test.test_db.TestMysql#test_accept_user", "labels": [{"name": "feature", "value": "DB tests"}, {"name": "epic", "value": "Awesome test application"}, {"name": "story", "value": "Accept user"}, {"name": "parentSuite", "value": "tests.db_test"}, {"name": "suite", "value": "test_db"}, {"name": "subSuite", "value": "TestMysql"}, {"name": "host", "value": "DESKTOP-LERA"}, {"name": "thread", "value": "6588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.db_test.test_db"}]}